common_permissions: &permissions
  permissions:
    - level: CAN_VIEW
      group_name: users


resources:
  jobs:
    app_deployment_job:
      parameters:
        - name: bundle_root
          default: ${workspace.file_path}
      name: ${bundle.target}-my_agent_project-app-deployment-job
      tasks:
        - task_key: AppDeployment
          notebook_task:
            notebook_path: ../agent_deployment/chat_interface_deployment/LaunchApp.py
            base_parameters:
              uc_catalog: ${var.uc_catalog}
              schema: ${var.schema}
              registered_model: ${var.registered_model}
              app_name: ${var.chatbot_name}
              # git source information of current ML resource deployment. It will be persisted as part of the workflow run
              git_source_info: url:${bundle.git.origin_url}; branch:${bundle.git.branch}; commit:${bundle.git.commit}
      
      schedule:
        # TODO: update this to reflect your schedule
        quartz_cron_expression: "0 0 12 1 1/1 ? * " # runs once a month at 12 am  
        pause_status: "PAUSED" # pausing as Apps are not used in this demo
        timezone_id: UTC
      <<: *permissions
      # If you want to turn on notifications for this job, please uncomment the below code,
      # and provide a list of emails to the on_failure argument.
      #
      #  email_notifications:
      #    on_failure:
      #      - first@company.com
      #      - second@company.com