# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under my_agent_project/resources/*
# and my_agent_project/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for my_agent_project Prod

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./my_agent_project

env:
  DATABRICKS_HOST: https://<instance>.cloud.databricks.com
  DATABRICKS_CLIENT_SECRET: ${{ secrets.PROD_DATABRICKS_CLIENT_SECRET }}
  DATABRICKS_CLIENT_ID: ${{ secrets.PROD_DATABRICKS_CLIENT_ID }}
  #DATABRICKS_TOKEN: ${{ secrets.PROD_WORKSPACE_TOKEN }}

jobs:
  prod:
    concurrency: my_agent_project-prod-bundle-job
    runs-on:
      group: <runner-group>
      labels: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.258.0
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t prod